//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;

public class Lava {
	public static int lavaYPos = -339;
	public static bool inLava(Vector3 vec) {
		if (vec.y <= lavaYPos) {
			return true;
		}
		return false;
	}
}


